env:
  - PYVER="3.6"

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n python-navaro python=$PYVER
  - conda update -q -n python-navaro -f environment.yml
  - source activate python-navaro

script: 
  - ipython -c "%run 00.Installation.py"
  - ipython -c "%run 01.Introduction.py"
  - ipython -c "%run 02.Strings.py"
  - ipython -c "%run 03.Lists.py"
  - ipython -c "%run 04.Control.Flow.Tools.py"
  - ipython -c "%run 05.Modules.py"
  - ipython -c "%run 06.Input.And.Output.py"
  - ipython -c "%run 07.Errors.and.Exceptions.py"
  - ipython -c "%run 08.Classes.py"
  - ipython -c "%run 09.Iterators.py"
  - ipython -c "%run 10.Multiprocessing.py"
  - ipython -c "%run 11.Standard.Library.py"
  - ipython -c "%run 12.Matplotlib.py"
  - ipython -c "%run 13.Numpy.py"
  - ipython -c "%run 14.SciPy.py"
  - ipython -c "%run 15.Sympy.py"
  - ipython -c "%run 16.Fortran.py"
  - ipython -c "%run 17.Cython.py"
  - ipython -c "%run 18.Numba.py"
  - ipython -c "%run 19.LandauDamping.py"
  - ipython -c "%run 20.Maxwell.2D.py"
  - ipython -c "%run 21.Gray.Scott.Model.py"
  - ipython -c "%run 22.Matplotlib.Animation.py"
